name: Deploy to Dev on Convox

on:
  push:
    branches:
      - 'develop'

env:
  # Required by Convox actions
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

concurrency: deploy-dev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ secrets.API_URL }}
      GTM_CONTAINER_ID: ${{ secrets.GTM_CONTAINER_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.2
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Remove dev dependencies
        run: yarn --production --frozen-lockfile
      - name: login
        id: login
        uses: convox/action-login@v1
        with:
          password: ${{ secrets.CONVOX_DEPLOY_KEY }}
          host: ${{ secrets.CONVOX_HOST }}
      - name: build
        id: build
        uses: convox/action-build@v1
        with:
          rack: pro
          app: dev-front-copotrzebne-pl
      - name: promote
        id: promote
        uses: convox/action-promote@v1
        with:
          rack: pro
          app: dev-front-copotrzebne-pl
          release: ${{ steps.build.outputs.release }}
